// Generated by scripts/brand-variants.mjs — do not edit by hand. Rerun the script when a
// brand background photograph changes.

export type BrandVariant = { name: string; hash: string; widths: number[] };

export const BRAND_VARIANTS: Record<string, BrandVariant> = {
  "/brand/hero-bg.jpg": {
    "name": "hero-bg",
    "hash": "8b533895d2",
    "widths": [
      640,
      960,
      1280,
      1920
    ]
  },
  "/brand/steppe-altai.jpg": {
    "name": "steppe-altai",
    "hash": "1b96c16a83",
    "widths": [
      640,
      960,
      1280,
      1600
    ]
  }
};
